volumes:
  platemate-data:
    external: true
  pg-admin:
    external: true
  jwtdown-db-data:
    external: true
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    environment:
      SIGNING_KEY:
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      DATABASE_URL: postgresql://platemate:platemate@db/platemate
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: platemate
      POSTGRES_USER: platemate
      POSTGRES_DB: platemate
    ports:
      - 15432:5432
    volumes:
      - platemate-data:/var/lib/postgresql/data

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: platemate@example.com
      PGADMIN_DEFAULT_PASSWORD: platemate
      PGADMIN_DISABLE_POSTFIX: 1
